# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_api', '0002_create_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokens',
            name='access_token_json',
        ),
        migrations.RemoveField(
            model_name='tokens',
            name='auth_token_json',
        ),
    ]
